before_script:
  - uname -a
language: ruby
rvm:
  - 1.9.3
  - 1.9.2
  - jruby-19mode
  - rbx-19mode
  - ruby-head
  - jruby-head
bundler_args: --without development
notifications:
  email:
    - gregory@wix.com